services:
  - type: web
    name: deezer-arl-generator
    env: node
    buildCommand: |
      npm install
      npm run install
    startCommand: npm start
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/playwright
