services:
  - type: web
    name: deezer-arl-generator
    env: node
    buildCommand: |
      npm install
      PLAYWRIGHT_BROWSERS_PATH=0 npm run install
    startCommand: npm start
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
